# 需要的环境变量
# MYSQL_ROOT_PASSWORD
# SUB_BASE_URL
# RSA_PUBLIC_KEY
# ADMIN_USERNAME
# ADMIN_PASSWORD
# RSA_PRIVATE_KEY

version: "3.0"
services:
  or-barrage-fly-mysql:
    image: or-barrage-fly-mysql
    container_name: or-barrage-fly-mysql
    build:
      context: ./or-barrage-fly-mysql
    volumes:
      - $PWD/or-barrage-fly-mysql/etc/my.cnf:/etc/my.cnf
      - $PWD/or-barrage-fly-mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
    hostname: or-barrage-fly-mysql
    restart: always

  or-barrage-fly-ui:
    image: or-barrage-fly-ui
    container_name: or-barrage-fly-ui
    build:
      context: ./or-barrage-fly-ui
    volumes:
      - $PWD/or-barrage-fly-ui/app:/ordinaryroad/or-barrage-fly-ui/app
    env_file:
      - ./or-barrage-fly-ui/.env
    environment:
      RSA_PUBLIC_KEY:
      SUB_BASE_URL:
    hostname: or-barrage-fly-ui
    restart: always

  or-barrage-fly:
    image: or-barrage-fly
    container_name: or-barrage-fly
    build:
      context: ./or-barrage-fly
    environment:
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ADMIN_USERNAME:
      ADMIN_PASSWORD:
      RSA_PUBLIC_KEY:
      RSA_PRIVATE_KEY:
    env_file:
      - ./or-barrage-fly/.env
    hostname: or-barrage-fly
    restart: always

  or-barrage-fly-nginx:
    image: or-barrage-fly-nginx
    container_name: or-barrage-fly-nginx
    build:
      context: ./or-barrage-fly-nginx
    ports:
      - "81:81"
      - "9898:9898"
    hostname: or-barrage-fly-nginx
    restart: always
