spring:
  application:
    name: ordinaryroad-barrage-fly
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://${MYSQL_HOST:ordinaryroad-barrage-fly-mysql}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:or_barrage_fly}?${MYSQL_PARAMS:useUnicode=true&characterEncoding=utf-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true}
          username: ${MYSQL_USERNAME:}
          password: ${MYSQL_PASSWORD:}
          driver-class-name: com.mysql.cj.jdbc.Driver
  integration:
    rsocket:
      server:
        message-mapping-enabled: true
  rsocket:
    server:
      port: 9898
      transport: websocket
  boot:
    admin:
      client:
        # https://barragefly.ordinaryroad.tech:7001/admin
        url: ${ADMIN_BASE_URL:http://localhost:8080/admin}
        username: ${ADMIN_USERNAME:admin}
        password: ${ADMIN_PASSWORD:admin}
      context-path: admin
      ui:
        public-url: ${ADMIN_BASE_URL:http://localhost:8080/admin}
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
  thymeleaf:
    check-template-location: false
sa-token:
  timeout: 60480 # 7天：3600*24*7
  token-name: token
  is-print: false
  basic: ${ADMIN_USERNAME:admin}:${ADMIN_PASSWORD:admin}
tech:
  ordinaryroad:
    barrage:
      fly:
        config:
          admin:
            username: ${ADMIN_USERNAME:admin}
            password: ${ADMIN_PASSWORD:admin}
            rsa-private-key: ${RSA_PRIVATE_KEY:}
            rsa-public-key: ${RSA_PUBLIC_KEY:}
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:}