# 需要的环境变量
# MYSQL_ROOT_PASSWORD
# SUB_BASE_URL
# RSA_PUBLIC_KEY
# ADMIN_USERNAME
# ADMIN_PASSWORD
# RSA_PRIVATE_KEY

version: "3.0"
services:
  ordinaryroad-barrage-fly-mysql:
    image: ordinaryroad-barrage-fly-mysql
    container_name: ordinaryroad-barrage-fly-mysql
    build:
      context: ./ordinaryroad-barrage-fly-mysql
    volumes:
      - $PWD/ordinaryroad-barrage-fly-mysql/etc/my.cnf:/etc/my.cnf
      - $PWD/ordinaryroad-barrage-fly-mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "33066:3306"
    hostname: ordinaryroad-barrage-fly-mysql
    restart: always

  ordinaryroad-barrage-fly-ui:
    image: ordinaryroad-barrage-fly-ui
    container_name: ordinaryroad-barrage-fly-ui
    build:
      context: ./ordinaryroad-barrage-fly-ui
    volumes:
      - $PWD/ordinaryroad-barrage-fly-ui/app:/ordinaryroad/ordinaryroad-barrage-fly-ui/app
    env_file:
      - ./ordinaryroad-barrage-fly-ui/.env
    environment:
      RSA_PUBLIC_KEY:
      SUB_BASE_URL:
    ports:
      - "30000:3000"
    hostname: ordinaryroad-barrage-fly-ui
    restart: always

  ordinaryroad-barrage-fly:
    image: ordinaryroad-barrage-fly
    container_name: ordinaryroad-barrage-fly
    build:
      context: ./ordinaryroad-barrage-fly
    environment:
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ADMIN_USERNAME:
      ADMIN_PASSWORD:
      RSA_PUBLIC_KEY:
      RSA_PRIVATE_KEY:
    env_file:
      - ./ordinaryroad-barrage-fly/.env
    ports:
      - "9898:9898"
    hostname: ordinaryroad-barrage-fly
    restart: always