# 需要的环境变量，其他可以环境变量可看每个目录下的.env文件
# MYSQL_HOST（注意请勿用localhost、127.0.0.1）
# MYSQL_PORT
# MYSQL_DATABASE
# MYSQL_USERNAME
# MYSQL_PASSWORD
# ADMIN_USERNAME（任务管理后台登录用户名，默认admin）
# ADMIN_PASSWORD（任务管理后台登录密码，默认admin）
# SPRING_BOOT_ADMIN_BASE_URL（根据后端部署情况设置Spring Boot Admin的地址）
# SUB_BASE_URL（根据后端部署情况设置Client要连接的WebSocket地址，注意请勿用localhost、127.0.0.1）

services:
  ordinaryroad-barrage-fly-ui:
    image: ordinaryroad-barrage-fly-ui
    container_name: ordinaryroad-barrage-fly-ui
    environment:
      BASE_URL: http://ordinaryroad-barrage-fly:8080
      SPRING_BOOT_ADMIN_BASE_URL: http://localhost:8080/admin
      SUB_BASE_URL:
    hostname: ordinaryroad-barrage-fly-ui
    restart: always

  ordinaryroad-barrage-fly:
    image: ordinaryroad-barrage-fly
    container_name: ordinaryroad-barrage-fly
    environment:
      MYSQL_HOST:
      MYSQL_PORT:
      MYSQL_DATABASE:
      MYSQL_USERNAME:
      MYSQL_PASSWORD:
      ADMIN_USERNAME:
      ADMIN_PASSWORD:
      JAVA_OPTS:
    hostname: ordinaryroad-barrage-fly
    restart: always

  ordinaryroad-barrage-fly-nginx:
    image: ordinaryroad-barrage-fly-nginx
    container_name: ordinaryroad-barrage-fly-nginx
    build:
      context: ./ordinaryroad-barrage-fly-nginx
    ports:
      # UI
      - "81:81"
      # Admin
      - "8080:8080"
      # 后端
      - "8081:8081"
      # RSocket
      - "9898:9898"
    hostname: ordinaryroad-barrage-fly-nginx
    depends_on:
      - ordinaryroad-barrage-fly
      - ordinaryroad-barrage-fly-ui
    restart: always
