name: Docker Image CI

on:
  workflow_dispatch:
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the ordinaryroad-barrage-fly Docker image
      run: |
        cd ./barrage-fly
        ./gradlew clean bootJar
        cd ../.docker/ordinaryroad-barrage-fly
        docker build . --file Dockerfile --tag ordinaryroad-barrage-fly:$(date +%s)
